-- Applied to Supabase project iwgcekvasxizdekjiacg on 2026-08-21.
-- Runtime uses the service-role connection for these backend-only tables.

create table if not exists public.company_ai_profiles (
  id bigint generated by default as identity primary key,
  company_id bigint not null unique references public.companies(id) on delete cascade,
  company_name text,
  description text,
  industry text,
  profile jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.company_ai_knowledge (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  knowledge_type text not null default 'fact',
  title text,
  content text not null,
  service_key text,
  source_type text,
  source_uri text,
  provider text,
  confidence numeric,
  metadata jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_company_ai_knowledge_company on public.company_ai_knowledge(company_id);
create index if not exists idx_company_ai_knowledge_service on public.company_ai_knowledge(company_id, service_key);
create index if not exists idx_company_ai_knowledge_active on public.company_ai_knowledge(company_id, is_active);

create table if not exists public.ai_learning_events (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  event_type text not null default 'council_observation',
  input_context jsonb not null default '{}'::jsonb,
  provider_outputs jsonb not null default '[]'::jsonb,
  decision jsonb not null default '{}'::jsonb,
  outcome jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_ai_learning_events_company on public.ai_learning_events(company_id, created_at desc);

alter table public.company_ai_profiles enable row level security;
alter table public.company_ai_knowledge enable row level security;
alter table public.ai_learning_events enable row level security;

create policy company_ai_profiles_no_direct_client_access on public.company_ai_profiles for all to anon, authenticated using (false) with check (false);
create policy company_ai_knowledge_no_direct_client_access on public.company_ai_knowledge for all to anon, authenticated using (false) with check (false);
create policy ai_learning_events_no_direct_client_access on public.ai_learning_events for all to anon, authenticated using (false) with check (false);
