-- Bitey Concept + Learning memory.
-- Apply this migration in Supabase before enabling durable learning.

create table if not exists public.bitey_concepts (
    id bigint generated by default as identity primary key,
    company_id bigint null,
    concept text not null,
    domain text not null default 'general',
    variants text[] not null default '{}',
    diagnostic_signals text[] not null default '{}',
    confidence numeric(5,4) not null default 0.70,
    source_count integer not null default 0,
    is_validated boolean not null default false,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (company_id, concept)
);

create table if not exists public.bitey_learning_events (
    id bigint generated by default as identity primary key,
    company_id bigint null,
    conversation_id text null,
    message text not null,
    language text not null default 'auto',
    intent text null,
    concept jsonb null,
    evidence jsonb not null default '[]'::jsonb,
    validated boolean not null default false,
    created_at timestamptz not null default now()
);

create index if not exists idx_bitey_concepts_company_active
    on public.bitey_concepts(company_id, is_active);
create index if not exists idx_bitey_learning_events_company_created
    on public.bitey_learning_events(company_id, created_at desc);

alter table public.bitey_concepts enable row level security;
alter table public.bitey_learning_events enable row level security;

-- Server-side FastAPI access uses the Supabase service role. No public client
-- policy is granted here; concepts are not exposed directly to browsers.
