create table if not exists public.bitey_problems (
  id bigint generated by default as identity primary key,
  company_id bigint not null,
  customer_id bigint not null references public.customers(id) on delete cascade,
  conversation_id bigint references public.conversations(id) on delete set null,
  ticket_id bigint references public.tickets(id) on delete set null,
  fingerprint text not null,
  state text not null default 'NEW_PROBLEM',
  category text,
  intent text,
  device_label text,
  device_platform text,
  problem_summary text,
  symptoms jsonb not null default '[]'::jsonb,
  evidence jsonb not null default '{}'::jsonb,
  confidence numeric not null default 0,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists bitey_problems_customer_fingerprint_uidx on public.bitey_problems(customer_id, fingerprint);
create index if not exists bitey_problems_customer_state_idx on public.bitey_problems(customer_id, state, last_seen_at desc);
create index if not exists bitey_problems_ticket_idx on public.bitey_problems(ticket_id);
alter table public.bitey_problems enable row level security;
