-- Bitey IA CRM Core
-- Additive migration: preserves existing customers, conversations and tickets.
-- Every CRM record is tenant-scoped by company_id.

create table if not exists public.crm_leads (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    customer_id bigint,
    conversation_id bigint,
    source text not null default 'web',
    status text not null default 'new',
    title text not null,
    description text,
    value numeric(14,2),
    currency text not null default 'BRL',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.crm_opportunities (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    customer_id bigint not null,
    lead_id bigint,
    conversation_id bigint,
    name text not null,
    stage text not null default 'qualification',
    status text not null default 'open',
    value numeric(14,2),
    currency text not null default 'BRL',
    probability numeric(5,2),
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.crm_sales (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    customer_id bigint not null,
    opportunity_id bigint,
    conversation_id bigint,
    service_id bigint,
    amount numeric(14,2) not null default 0,
    currency text not null default 'BRL',
    status text not null default 'pending',
    reference text,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.crm_services (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    customer_id bigint not null,
    sale_id bigint,
    ticket_id bigint,
    name text not null,
    status text not null default 'requested',
    description text,
    scheduled_at timestamptz,
    completed_at timestamptz,
    amount numeric(14,2),
    currency text not null default 'BRL',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_crm_leads_company_status on public.crm_leads(company_id, status, updated_at desc);
create index if not exists idx_crm_leads_customer on public.crm_leads(company_id, customer_id);
create index if not exists idx_crm_opportunities_company_stage on public.crm_opportunities(company_id, stage, updated_at desc);
create index if not exists idx_crm_opportunities_customer on public.crm_opportunities(company_id, customer_id);
create index if not exists idx_crm_sales_company_status on public.crm_sales(company_id, status, updated_at desc);
create index if not exists idx_crm_sales_customer on public.crm_sales(company_id, customer_id);
create index if not exists idx_crm_services_company_status on public.crm_services(company_id, status, updated_at desc);
create index if not exists idx_crm_services_customer on public.crm_services(company_id, customer_id);

create or replace function public.crm_set_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_crm_leads_updated_at on public.crm_leads;
create trigger trg_crm_leads_updated_at before update on public.crm_leads for each row execute function public.crm_set_updated_at();
drop trigger if exists trg_crm_opportunities_updated_at on public.crm_opportunities;
create trigger trg_crm_opportunities_updated_at before update on public.crm_opportunities for each row execute function public.crm_set_updated_at();
drop trigger if exists trg_crm_sales_updated_at on public.crm_sales;
create trigger trg_crm_sales_updated_at before update on public.crm_sales for each row execute function public.crm_set_updated_at();
drop trigger if exists trg_crm_services_updated_at on public.crm_services;
create trigger trg_crm_services_updated_at before update on public.crm_services for each row execute function public.crm_set_updated_at();

-- The backend authenticates Portal users and scopes every query by company_id.
-- RLS can be enabled later when direct browser access is introduced.
