-- Company-scoped AI intelligence and learning index.
-- These tables intentionally keep company_id generic so they can attach to the
-- existing BiteFixes company registry without changing existing tables.

create table if not exists public.company_ai_profiles (
    id bigint generated by default as identity primary key,
    company_id bigint not null unique,
    company_name text,
    description text,
    industry text,
    profile jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

create table if not exists public.company_ai_knowledge (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    knowledge_type text not null default 'fact',
    title text,
    content text not null,
    service_key text,
    source_type text,
    source_uri text,
    provider text,
    confidence numeric,
    metadata jsonb not null default '{}'::jsonb,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create index if not exists idx_company_ai_knowledge_company
    on public.company_ai_knowledge(company_id);

create index if not exists idx_company_ai_knowledge_company_service
    on public.company_ai_knowledge(company_id, service_key);

create index if not exists idx_company_ai_knowledge_type
    on public.company_ai_knowledge(company_id, knowledge_type);

create table if not exists public.ai_learning_events (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    event_type text not null default 'council_observation',
    input_context jsonb not null default '{}'::jsonb,
    provider_outputs jsonb not null default '[]'::jsonb,
    decision jsonb not null default '{}'::jsonb,
    outcome jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_ai_learning_events_company
    on public.ai_learning_events(company_id, created_at desc);
